train_image_path : "/datasets/hdd/dataset/ADEChallengeData2016/train_images.txt"
train_mask_path : "/datasets/hdd/dataset/ADEChallengeData2016/train_gts.txt"
valid_image_path : "/datasets/hdd/dataset/ADEChallengeData2016/valid_images.txt"
valid_mask_path : "/datasets/hdd/dataset/ADEChallengeData2016/valid_gts.txt"
image_size : [480, 480]
batch_size : 8
dataset_name : "ade20k"
model_name : "bisenet"

lr : 0.0001
lr_decay : 0.002

gpu_indices : [0, 1]

num_classes : 151
class_weight : []
class_color_map : []

# 0 : train from 0, 1 : train continue, 2 : test
mode : 1
present_epoch : 50
epoch : 200
saving_interval : 10
save_best : True

save_path : "/dy/weights/ade20k_bisenet"
serving_save_path : "/dy/serving_weights/ade20k_bisenet"
logger_file : "/dy/logs/ade20k_bisenet.csv"


model :
    c : 0

test :
    best : True
    best_file_name : "best.h5"
    # best_file_name : "model_50.h5"
    eval : True
    output_folder : "/dy/outputs/ade20k_bisenet"

